package com.trybe.calcularidade.exception;

public class DataFuturaException extends RuntimeException {

  public DataFuturaException() {
    super("Data Futura");
  }


}
